events {}

http {
  server {
    listen 80;
    server_name _;

    location /api/ {
      proxy_pass http://backend:8000/;
    }

    location = /phpmyadmin {
      return 301 /phpmyadmin/;
    }

    location /phpmyadmin/ {
      auth_basic "Área Restringida - Base de Datos";
      auth_basic_user_file /etc/nginx/.htpasswd;
      proxy_pass http://phpmyadmin:80/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /poo_phpmyadmin {
      return 301 /poo_phpmyadmin/;
    }

    location /poo_phpmyadmin/ {
      return 301 /phpmyadmin/;
    }

    location / {
      proxy_pass http://frontend:4173/;
    }
  }
}